export { companyList }

const companyList = Promise.resolve(() => ({
  title: '国内创业公司,优质创业项目 | IT桔子',
  data: [
    {
      agg_born_time: '2015-06-01',
      born_time: 1433088000,
      year: 2015,
      city: '南京',
      round: '尚未获投',
      month: 6,
      scope: '文娱传媒',
      name: '穆环传媒',
      logo: 'https://cdn.itjuzi.com/images/2d6a678557a85bc20a5642ef439458ac.png',
      id: 39263926,
      tag: [
        {
          tag_name: '模特',
          tag_id: 526,
        },
        {
          tag_name: '影视',
          tag_id: 724,
        },
        {
          tag_name: '综合文娱',
          tag_id: 949,
        },
        {
          tag_name: '文化娱乐',
          tag_id: 950,
        },
        {
          tag_name: '文娱传媒',
          tag_id: 3365,
        },
        {
          tag_name: '影视制作',
          tag_id: 3737,
        },
        {
          tag_name: '演出/演艺',
          tag_id: 8166,
        },
        {
          tag_name: '影视发行',
          tag_id: 8169,
        },
      ],
      total_money: '-',
      prov: '江苏',
      slogan: '综合文娱服务商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2019-07-01',
      born_time: 1561910400,
      year: 2019,
      city: '商丘',
      round: '尚未获投',
      month: 7,
      scope: '文娱传媒',
      name: '伟仔文化',
      logo: 'https://cdn.itjuzi.com/images/20607b458990d42716559e234fd607cf.png',
      id: 39263900,
      tag: [
        {
          tag_name: '直播',
          tag_id: 17,
        },
        {
          tag_name: '视频',
          tag_id: 266,
        },
        {
          tag_name: '舞蹈',
          tag_id: 840,
        },
        {
          tag_name: '文化娱乐',
          tag_id: 950,
        },
        {
          tag_name: '短视频',
          tag_id: 1227,
        },
        {
          tag_name: '文娱传媒',
          tag_id: 3365,
        },
        {
          tag_name: '艺人网红',
          tag_id: 3524,
        },
        {
          tag_name: '文艺演出',
          tag_id: 3710,
        },
        {
          tag_name: '演出/演艺',
          tag_id: 8166,
        },
        {
          tag_name: '视频直播',
          tag_id: 8187,
        },
        {
          tag_name: '主播',
          tag_id: 8191,
        },
      ],
      total_money: '-',
      prov: '河南',
      slogan: '孵化网红培训平台',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2019-12-01',
      born_time: 1575129600,
      year: 2019,
      city: '成都',
      round: '尚未获投',
      month: 12,
      scope: '企业服务',
      name: '君师汇',
      logo: 'https://cdn.itjuzi.com/images/e0b5efdd6ff5801c210f67e8dcc2fe66.png',
      id: 39263861,
      tag: [
        {
          tag_name: '企业服务',
          tag_id: 737,
        },
        {
          tag_name: '其他企业服务',
          tag_id: 745,
        },
        {
          tag_name: '咨询服务',
          tag_id: 811,
        },
        {
          tag_name: '企业培训',
          tag_id: 847,
        },
        {
          tag_name: '管理培训',
          tag_id: 1314,
        },
      ],
      total_money: '-',
      prov: '四川',
      slogan: '企业培训咨询机构',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2017-10-01',
      born_time: 1506787200,
      year: 2017,
      city: '深圳',
      round: '尚未获投',
      month: 10,
      scope: '金融',
      name: '深圳易宝信息',
      logo: 'https://cdn.itjuzi.com/images/67a013d2e1354b5568ee643c7d39d9b1.png',
      id: 39263845,
      tag: [
        {
          tag_name: '金融',
          tag_id: 609,
        },
        {
          tag_name: '金融综合服务',
          tag_id: 624,
        },
        {
          tag_name: '企业融资',
          tag_id: 4464,
        },
        {
          tag_name: '企业金融',
          tag_id: 6929,
        },
        {
          tag_name: '担保',
          tag_id: 6945,
        },
        {
          tag_name: '抵押贷款',
          tag_id: 6946,
        },
      ],
      total_money: '-',
      prov: '广东',
      slogan: '多元化金融服务提供商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2020-05-01',
      born_time: 1588262400,
      year: 2020,
      city: '徐汇区',
      round: '尚未获投',
      month: 5,
      scope: '企业服务',
      name: '亿眸电子',
      logo: 'https://cdn.itjuzi.com/images/b54f28c0b94e9997b7038b188bc26524.png',
      id: 39263752,
      tag: [
        {
          tag_name: '企业服务',
          tag_id: 737,
        },
        {
          tag_name: '前沿技术',
          tag_id: 1243,
        },
        {
          tag_name: '行业方案',
          tag_id: 5515,
        },
        {
          tag_name: '互联网智能化',
          tag_id: 5679,
        },
        {
          tag_name: 'AI',
          tag_id: 7646,
        },
        {
          tag_name: '芯片设计',
          tag_id: 12842,
        },
      ],
      total_money: '-',
      prov: '上海',
      slogan: '智能技术系统方案供应商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2018-07-01',
      born_time: 1530374400,
      year: 2018,
      city: '美国',
      round: 'B轮',
      month: 7,
      scope: '区块链',
      name: 'NEAR Protocol',
      logo: 'https://cdn.itjuzi.com/images/6a6df954634ae92a33cffc87a12fda83.png',
      id: 39263713,
      tag: [
        {
          tag_name: '人工智能',
          tag_id: 247,
        },
        {
          tag_name: '区块链',
          tag_id: 1170,
        },
        {
          tag_name: '智能合约',
          tag_id: 5062,
        },
        {
          tag_name: '区块链应用技术',
          tag_id: 5327,
        },
        {
          tag_name: '区块链行业应用',
          tag_id: 5330,
        },
        {
          tag_name: '区块链工具',
          tag_id: 5354,
        },
      ],
      total_money: '11亿人民币',
      prov: '北美洲',
      slogan: '区块链分布式协议提供商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2019-07-01',
      born_time: 1561910400,
      year: 2019,
      city: '西安',
      round: '尚未获投',
      month: 7,
      scope: '物流',
      name: '鼎喜旺',
      logo: 'https://cdn.itjuzi.com/images/c0dae80ee717aab19d010de9fcc444bf.png',
      id: 39263634,
      tag: [
        {
          tag_name: '同城配送',
          tag_id: 816,
        },
        {
          tag_name: '物流',
          tag_id: 973,
        },
        {
          tag_name: '配送服务',
          tag_id: 3402,
        },
        {
          tag_name: '物流管理',
          tag_id: 3403,
        },
        {
          tag_name: '物流服务',
          tag_id: 5051,
        },
        {
          tag_name: '物流运输',
          tag_id: 8401,
        },
        {
          tag_name: '物流供应链',
          tag_id: 9108,
        },
        {
          tag_name: '配送',
          tag_id: 9244,
        },
        {
          tag_name: '同城物流',
          tag_id: 10461,
        },
        {
          tag_name: '供应链物流',
          tag_id: 11597,
        },
      ],
      total_money: '-',
      prov: '陕西',
      slogan: '中短途物流配送服务商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2014-07-01',
      born_time: 1404144000,
      year: 2014,
      city: '浦东新区',
      round: '尚未获投',
      month: 7,
      scope: '教育',
      name: '成北石蒙教育',
      logo: 'https://cdn.itjuzi.com/images/cbd7940c4e694be6825e71ad451e677c.jpg',
      id: 39263567,
      tag: [
        {
          tag_name: '教育',
          tag_id: 597,
        },
        {
          tag_name: '教育综合服务',
          tag_id: 607,
        },
        {
          tag_name: '中小学教育',
          tag_id: 5185,
        },
        {
          tag_name: 'K12教育',
          tag_id: 6845,
        },
        {
          tag_name: '教师培训',
          tag_id: 6860,
        },
        {
          tag_name: '学校/院校',
          tag_id: 6879,
        },
        {
          tag_name: '教育资源',
          tag_id: 9906,
        },
        {
          tag_name: '泛教育',
          tag_id: 9969,
        },
      ],
      total_money: '-',
      prov: '上海',
      slogan: '教育综合服务商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2012-08-01',
      born_time: 1343750400,
      year: 2012,
      city: '青浦区',
      round: '尚未获投',
      month: 8,
      scope: '生产制造',
      name: '侨谊',
      logo: 'https://cdn.itjuzi.com/images/7569221c925901438db1790c4ba354e9.png',
      id: 39263500,
      tag: [
        {
          tag_name: '生产制造',
          tag_id: 1181,
        },
        {
          tag_name: '电气设备',
          tag_id: 1224,
        },
        {
          tag_name: '机械设备',
          tag_id: 11018,
        },
      ],
      total_money: '-',
      prov: '上海',
      slogan: '电气设备生产制造商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2021-04-01',
      born_time: 1617206400,
      year: 2021,
      city: '杭州',
      round: '尚未获投',
      month: 4,
      scope: '企业服务',
      name: '思普盟',
      logo: 'https://cdn.itjuzi.com/images/34723ba24d8933730456e6d670bcff3c.png',
      id: 39263449,
      tag: [
        {
          tag_name: '教育信息化',
          tag_id: 606,
        },
        {
          tag_name: '企业服务',
          tag_id: 737,
        },
        {
          tag_name: '前沿技术',
          tag_id: 1243,
        },
        {
          tag_name: '智慧教育',
          tag_id: 1359,
        },
        {
          tag_name: '在线教育平台',
          tag_id: 4315,
        },
        {
          tag_name: 'K12教育',
          tag_id: 6845,
        },
      ],
      total_money: '-',
      prov: '浙江',
      slogan: '科技技术服务提供商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2019-07-01',
      born_time: 1561910400,
      year: 2019,
      city: '奉贤区',
      round: '尚未获投',
      month: 7,
      scope: '文娱传媒',
      name: '炽热传媒',
      logo: 'https://cdn.itjuzi.com/images/6b66fc88a9bcd1f856ba5484d7d02661.png',
      id: 39263356,
      tag: [
        {
          tag_name: '直播',
          tag_id: 17,
        },
        {
          tag_name: '视频',
          tag_id: 266,
        },
        {
          tag_name: '文化娱乐',
          tag_id: 950,
        },
        {
          tag_name: '短视频',
          tag_id: 1227,
        },
        {
          tag_name: '文娱传媒',
          tag_id: 3365,
        },
        {
          tag_name: '艺人网红',
          tag_id: 3524,
        },
        {
          tag_name: '直播平台',
          tag_id: 3713,
        },
        {
          tag_name: '配音配乐',
          tag_id: 3768,
        },
        {
          tag_name: '视频直播',
          tag_id: 8187,
        },
        {
          tag_name: '网红孵化',
          tag_id: 8218,
        },
      ],
      total_money: '-',
      prov: '上海',
      slogan: '短视频网红直播平台',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2004-11-01',
      born_time: 1099238400,
      year: 2004,
      city: '渝北区',
      round: '尚未获投',
      month: 11,
      scope: '汽车交通',
      name: '津住汽车',
      logo: 'https://cdn.itjuzi.com/images/5ea4c3584b78938758129d1027515252.png',
      id: 39263326,
      tag: [
        {
          tag_name: '汽车配件',
          tag_id: 55,
        },
        {
          tag_name: '汽车交通',
          tag_id: 627,
        },
        {
          tag_name: '汽车后服务',
          tag_id: 630,
        },
        {
          tag_name: '汽车制造',
          tag_id: 1455,
        },
        {
          tag_name: '汽车零部件',
          tag_id: 4630,
        },
        {
          tag_name: '汽车后市场',
          tag_id: 7507,
        },
        {
          tag_name: '行',
          tag_id: 8446,
        },
      ],
      total_money: '-',
      prov: '重庆',
      slogan: '汽车线束制造商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2021-03-01',
      born_time: 1614528000,
      year: 2021,
      city: '深圳',
      round: '尚未获投',
      month: 3,
      scope: '医疗健康',
      name: '瑞平健康',
      logo: 'https://cdn.itjuzi.com/images/3b108fa2e25ab41ade4be112106f2fbe.png',
      id: 39263298,
      tag: [
        {
          tag_name: '医疗健康',
          tag_id: 649,
        },
        {
          tag_name: '专科服务',
          tag_id: 656,
        },
        {
          tag_name: '健康保健',
          tag_id: 931,
        },
        {
          tag_name: '健康管理',
          tag_id: 1279,
        },
        {
          tag_name: '数字化服务平台',
          tag_id: 5246,
        },
        {
          tag_name: '医疗专科服务',
          tag_id: 8511,
        },
      ],
      total_money: '-',
      prov: '广东',
      slogan: '医疗健康数字化服务提供商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2021-10-01',
      born_time: 1633017600,
      year: 2021,
      city: '浦东新区',
      round: '尚未获投',
      month: 10,
      scope: '本地生活',
      name: '盼库商业',
      logo: 'https://cdn.itjuzi.com/images/7d17f64601eba0ce6d659f87ffbb18c1.png',
      id: 39263278,
      tag: [
        {
          tag_name: '本地生活',
          tag_id: 674,
        },
        {
          tag_name: '商户服务及信息化',
          tag_id: 685,
        },
        {
          tag_name: '其他生活服务',
          tag_id: 935,
        },
        {
          tag_name: '生活服务',
          tag_id: 1379,
        },
        {
          tag_name: '折扣优惠',
          tag_id: 7977,
        },
      ],
      total_money: '-',
      prov: '上海',
      slogan: '全品类线上线下折扣销售平台',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2021-07-01',
      born_time: 1625068800,
      year: 2021,
      city: '成都',
      round: '尚未获投',
      month: 7,
      scope: '电子商务',
      name: '久功信息',
      logo: 'https://cdn.itjuzi.com/images/ed2f9986037770c386ee1d9fc4922518.png',
      id: 39263207,
      tag: [
        {
          tag_name: '电子商务',
          tag_id: 756,
        },
        {
          tag_name: '跨境电商',
          tag_id: 963,
        },
        {
          tag_name: '销售',
          tag_id: 1183,
        },
        {
          tag_name: '产品研发',
          tag_id: 3915,
        },
        {
          tag_name: '互联网',
          tag_id: 4615,
        },
        {
          tag_name: '电商支撑服务',
          tag_id: 6275,
        },
      ],
      total_money: '-',
      prov: '四川',
      slogan: '跨境电商服务商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2005-11-01',
      born_time: 1130774400,
      year: 2005,
      city: '泰安',
      round: '尚未获投',
      month: 11,
      scope: '本地生活',
      name: '百合股份',
      logo: 'https://cdn.itjuzi.com/images/87a662c82e8a4ceb80c4f0277321ff13.png',
      id: 39263163,
      tag: [
        {
          tag_name: '本地生活',
          tag_id: 674,
        },
        {
          tag_name: '酒水饮料',
          tag_id: 1220,
        },
        {
          tag_name: '生活服务',
          tag_id: 1379,
        },
        {
          tag_name: '养生保健',
          tag_id: 4224,
        },
        {
          tag_name: '美妆',
          tag_id: 7936,
        },
        {
          tag_name: '养生服务',
          tag_id: 7968,
        },
        {
          tag_name: '食品饮料',
          tag_id: 10099,
        },
      ],
      total_money: '-',
      prov: '山东',
      slogan: '膳食营养品生产商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2015-09-01',
      born_time: 1441036800,
      year: 2015,
      city: '广州',
      round: '尚未获投',
      month: 9,
      scope: '电子商务',
      name: '广颖创',
      logo: 'https://cdn.itjuzi.com/images/270cb5b6605b502ffcace949212ec32c.png',
      id: 39263100,
      tag: [
        {
          tag_name: 'B2B',
          tag_id: 402,
        },
        {
          tag_name: '电子商务',
          tag_id: 756,
        },
        {
          tag_name: '跨境电商',
          tag_id: 963,
        },
        {
          tag_name: '进出口贸易',
          tag_id: 4178,
        },
        {
          tag_name: '电商支撑服务',
          tag_id: 6275,
        },
        {
          tag_name: '电商供应链',
          tag_id: 6319,
        },
      ],
      total_money: '-',
      prov: '广东',
      slogan: '跨境电商服务商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2005-06-01',
      born_time: 1117555200,
      year: 2005,
      city: '海淀区',
      round: '尚未获投',
      month: 6,
      scope: '企业服务',
      name: '中科国技',
      logo: 'https://cdn.itjuzi.com/images/4f5c22303bfeb9436db7b08d59039138.png',
      id: 39263074,
      tag: [
        {
          tag_name: '企业服务',
          tag_id: 737,
        },
        {
          tag_name: '前沿技术',
          tag_id: 1243,
        },
        {
          tag_name: '无线通信',
          tag_id: 5545,
        },
        {
          tag_name: '5G',
          tag_id: 10004,
        },
      ],
      total_money: '-',
      prov: '北京',
      slogan: '无线通信及射频微波测试产品公司',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2021-07-01',
      born_time: 1625068800,
      year: 2021,
      city: '海淀区',
      round: '尚未获投',
      month: 7,
      scope: '企业服务',
      name: '白海科技',
      logo: 'https://cdn.itjuzi.com/images/e7bdac1a424cd7eef36ecf6a76bc759d.png',
      id: 39263027,
      tag: [
        {
          tag_name: '人工智能',
          tag_id: 247,
        },
        {
          tag_name: '企业服务',
          tag_id: 737,
        },
        {
          tag_name: '工具软件',
          tag_id: 775,
        },
        {
          tag_name: '云服务',
          tag_id: 3449,
        },
        {
          tag_name: '人工智能算法',
          tag_id: 3948,
        },
        {
          tag_name: '智能算法',
          tag_id: 4086,
        },
        {
          tag_name: '基础层',
          tag_id: 7642,
        },
        {
          tag_name: '开发平台',
          tag_id: 10056,
        },
      ],
      total_money: '-',
      prov: '北京',
      slogan: '云原生AI基础软件平台服务商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
    {
      agg_born_time: '2017-09-01',
      born_time: 1504195200,
      year: 2017,
      city: '嘉定区',
      round: '尚未获投',
      month: 9,
      scope: '文娱传媒',
      name: '白宙动画工作室',
      logo: 'https://cdn.itjuzi.com/images/3d558ab419e5508a3a47d8ac3534df2d.png',
      id: 39262987,
      tag: [
        {
          tag_name: '电影',
          tag_id: 260,
        },
        {
          tag_name: '影视',
          tag_id: 724,
        },
        {
          tag_name: '动漫',
          tag_id: 725,
        },
        {
          tag_name: '文化娱乐',
          tag_id: 950,
        },
        {
          tag_name: '文娱传媒',
          tag_id: 3365,
        },
        {
          tag_name: '动画制作',
          tag_id: 5540,
        },
        {
          tag_name: '动漫制作',
          tag_id: 8206,
        },
      ],
      total_money: '-',
      prov: '上海',
      slogan: '动画制作提供商',
      follow_status: false,
      track_status: false,
      notes: {},
      has_report: false,
    },
  ],
}))
